# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso_responsable',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcesApp.Responsable'),
        ),
    ]
