# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0002_auto_20181103_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso_Revisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcesApp.Recurso')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcesApp.Responsable')),
            ],
        ),
        migrations.AlterField(
            model_name='recurso_responsable',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcesApp.Responsable'),
        ),
    ]
