# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0002_auto_20181115_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to='resourcesApp.Responsable'),
        ),
    ]
