# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0002_auto_20181028_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso_Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso', to='resourcesApp.Recurso')),
            ],
        ),
    ]
