# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0004_recurso_comentario_revisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Recurso',
            new_name='TipoRecurso',
        ),
    ]
